[package]
name = "manual-command"
version = "0.1.0"
authors = ["Daniel Olano <danielolanoc@gmail.com>"]
edition = "2018"

[dependencies]
device_query = "0.2.3"
futures = "0.3.4"
async-std = { version = "1.5.0", features = ["attributes", "unstable"] }
